cciDBsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('interactions/', include('interactions.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='interactions/', permanent=True)),
]

urlpatterns += [
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

interactions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.help, name = 'about'),
    path('pathways/', views.PathwayListView.as_view(), name = 'pathways'),
    path('pathways/<int:pk>', views.PathwayDetailView.as_view(), name = 'pathway-detail'),
    path('cellclasses/', views.CellClassListView.as_view(), name = 'cellclasses'),
    path('cellclasses/<int:pk>', views.CellClassDetailView.as_view(), name = 'cellclass-detail'),
    path('genes/', views.genes, name = 'genes'),
    path('ligand/<int:pk>', views.LigandDetailView.as_view(), name = 'ligand-detail'),
    path('receptor/<int:pk>', views.ReceptorDetailView.as_view(), name = 'receptor-detail'),
    path('correlations/', views.correlations, name = 'correlations')
]

interactions/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Pathway(models.Model):
    """Model representing a biological pathway"""
    
    PATH_STATUS = (
        ('c', 'Cell-Cell Contact'),
        ('e', 'ECM-Receptor'),
        ('s', 'Secreted Signaling')
    )

    name = models.CharField(max_length = 10)
    interaction_type = models.CharField(max_length = 1, choices = PATH_STATUS, default = 's')
    hscPercent = models.FloatField()

    ligands = models.ManyToManyField('Ligand', related_name='pathway_ligand')
    receptors = models.ManyToManyField('Receptor', related_name='pathway_receptor')

    evidences = models.TextField(default = '')

    class Meta:
        ordering = ['interaction_type', 'name']

    def __str__(self):
        """String for representing a Model object."""
        return self.name
        
    @property
    def get_absolute_url(self):
        return reverse('pathway-detail', args=[str(self.id)])

    def get_pathway_number(self):
        co = pathwayAndCelltype.objects.filter(pathway = self).filter(hscPercent__gt=0.05).count()
        return int(co)
    
    def get_highest_interaction_score(self):
        co = pathwayAndCelltype.objects.filter(pathway = self).filter(hscPercent__gt=0.05)
        maxi = 0
        for c in co:
            if c.averageScore > maxi:
                maxi = c.averageScore
        return float(maxi)

class cellClas(models.Model):
    
    CELL_STATUS = (
        ('n', 'Non-hematopoietic'),
        ('i', 'Blood & Immune Cells'),
        ('p', 'HPC')
    )
    
    name = models.CharField(max_length=50)
    sendingPathways = models.ManyToManyField(Pathway, related_name='sendingPathways')
    receivingPathways = models.ManyToManyField(Pathway, related_name='receivingPathways')

    cell_type = models.CharField(max_length = 1, choices = CELL_STATUS, default = 'n')

    class Meta:
        ordering = ['cell_type', 'name']

    def __str__(self):
        return self.name

    @property
    def get_absolute_url(self):
        return reverse('cellclass-detail', args=[str(self.id)])

    def get_pathway_number(self):
        co = pathwayAndCelltype.objects.filter(celltype = self).filter(hscPercent__gt=0.05).count()
        return int(co)
    
    def get_highest_interaction_score(self):
        co = pathwayAndCelltype.objects.filter(celltype = self).filter(hscPercent__gt=0.05)
        maxi = 0
        for c in co:
            if c.averageScore > maxi:
                maxi = c.averageScore
        return float(maxi)

class Ligand(models.Model):
    name = models.CharField(max_length = 10)
    receptors = models.ManyToManyField('Receptor')
    pathways = models.ManyToManyField(Pathway)
    evidences = models.TextField(default = '')

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ligand-detail', args=[str(self.id)])

class Receptor(models.Model):
    name = models.CharField(max_length = 10)
    ligands = models.ManyToManyField(Ligand)
    pathways = models.ManyToManyField(Pathway)
    evidences = models.TextField(default = '')
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('receptor-detail', args=[str(self.id)])

class pathwayAndCelltype(models.Model):
    
    SIGNAL_STATUS = (
        ('s', 'Sending'),
        ('r', 'Receiving')
    )

    pathway = models.ForeignKey(Pathway,on_delete=models.SET_NULL, null=True)
    celltype = models.ForeignKey(cellClas,on_delete=models.SET_NULL, null=True)
    hscPercent = models.FloatField(default = 0)
    averageScore = models.FloatField(default = 0)
    
    sorr = models.CharField(max_length = 1, choices = SIGNAL_STATUS, default = 's')
    
    class Meta:
        ordering = ['sorr', 'pathway', 'celltype', '-hscPercent', '-averageScore']

    def __str__(self):
        return self.pathway.name + "_" + self.celltype.name + "_" + self.sorr

class pathwayCorrelations(models.Model):
    
    SIGNAL_STATUS = (
        ('s', 'Sending'),
        ('r', 'Receiving')
    )

    pathway1 = models.ForeignKey(Pathway,on_delete=models.SET_NULL, null=True, related_name='pathway1')
    p1a = models.CharField(max_length = 1, choices = SIGNAL_STATUS, default = 's')
    pathway2 = models.ForeignKey(Pathway,on_delete=models.SET_NULL, null=True, related_name='pathway2')
    p2a = models.CharField(max_length = 1, choices = SIGNAL_STATUS, default = 's')
    correlation = models.FloatField(default = 0)
    pval = models.FloatField(default = 0)

interactions/views.py
from django.shortcuts import render
from plotly.offline import plot
import plotly.graph_objects as go
from django.shortcuts import get_object_or_404
import networkx as nx
import json
import numpy as np
from matplotlib import cm
import matplotlib as mpl
from .models import Pathway, Receptor, Ligand, cellClas, pathwayAndCelltype, pathwayCorrelations
from django.views import generic
# Create your views here.

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 15 11:45:07 2020
@author: aransil
"""

greys = cm.get_cmap('Greys', 10000)


import math
from typing import List
from itertools import chain

# n is number of points to place evenly in a circle centered around (0,0)
def circle(n):
    x = []
    y = []
    for i in range(0,n):
        angle = (i/n)*math.pi*2
        x.append(math.cos(angle))
        y.append(math.sin(angle))
    
    return x, y

# Start and end are lists defining start and end points
# Edge x and y are lists used to construct the graph
# arrowAngle and arrowLength define properties of the arrowhead
# arrowPos is None, 'middle' or 'end' based on where on the edge you want the arrow to appear
# arrowLength is the length of the arrowhead
# arrowAngle is the angle in degrees that the arrowhead makes with the edge
# dotSize is the plotly scatter dot size you are using (used to even out line spacing when you have a mix of edge lengths)
def addEdge(start, end, edge_x, edge_y, lengthFrac=1, arrowPos = None, arrowLength=0.025, arrowAngle = 30, dotSize=20):

    # Get start and end cartesian coordinates
    x0, y0 = start
    x1, y1 = end

    # Incorporate the fraction of this segment covered by a dot into total reduction
    length = math.sqrt( (x1-x0)**2 + (y1-y0)**2 )
    dotSizeConversion = .0565/20 # length units per dot size
    convertedDotDiameter = dotSize * dotSizeConversion
    lengthFracReduction = convertedDotDiameter / length
    lengthFrac = lengthFrac - lengthFracReduction

    # If the line segment should not cover the entire distance, get actual start and end coords
    skipX = (x1-x0)*(1-lengthFrac)
    skipY = (y1-y0)*(1-lengthFrac)
    x0 = x0 + skipX/2
    x1 = x1 - skipX/2
    y0 = y0 + skipY/2
    y1 = y1 - skipY/2

    # Append line corresponding to the edge
    edge_x.append(x0)
    edge_x.append(x1)
    edge_x.append(None) # Prevents a line being drawn from end of this edge to start of next edge
    edge_y.append(y0)
    edge_y.append(y1)
    edge_y.append(None)

    # Draw arrow
    if not arrowPos == None:

        # Find the point of the arrow; assume is at end unless told middle
        pointx = x1
        pointy = y1

        eta = math.degrees(math.atan((x1-x0)/(y1-y0))) if y1!=y0 else 90.0

        if arrowPos == 'middle' or arrowPos == 'mid':
            pointx = x0 + (x1-x0)/2
            pointy = y0 + (y1-y0)/2

        # Find the directions the arrows are pointing
        signx = (x1-x0)/abs(x1-x0) if x1!=x0 else +1    #verify this once
        signy = (y1-y0)/abs(y1-y0) if y1!=y0 else +1    #verified

        # Append first arrowhead
        dx = arrowLength * math.sin(math.radians(eta + arrowAngle))
        dy = arrowLength * math.cos(math.radians(eta + arrowAngle))
        edge_x.append(pointx)
        edge_x.append(pointx - signx**2 * signy * dx)
        edge_x.append(None)
        edge_y.append(pointy)
        edge_y.append(pointy - signx**2 * signy * dy)
        edge_y.append(None)

        # And second arrowhead
        dx = arrowLength * math.sin(math.radians(eta - arrowAngle))
        dy = arrowLength * math.cos(math.radians(eta - arrowAngle))
        edge_x.append(pointx)
        edge_x.append(pointx - signx**2 * signy * dx)
        edge_x.append(None)
        edge_y.append(pointy)
        edge_y.append(pointy - signx**2 * signy * dy)
        edge_y.append(None)


    return edge_x, edge_y

def add_arrows(source_x: List[float], target_x: List[float], source_y: List[float], target_y: List[float],
               arrowLength=0.025, arrowAngle=30):
    pointx = list(map(lambda x: x[0] + (x[1] - x[0]) / 2, zip(source_x, target_x)))
    pointy = list(map(lambda x: x[0] + (x[1] - x[0]) / 2, zip(source_y, target_y)))
    etas = list(map(lambda x: math.degrees(math.atan((x[1] - x[0]) / (x[3] - x[2]))),
                    zip(source_x, target_x, source_y, target_y)))

    signx = list(map(lambda x: (x[1] - x[0]) / abs(x[1] - x[0]), zip(source_x, target_x)))
    signy = list(map(lambda x: (x[1] - x[0]) / abs(x[1] - x[0]), zip(source_y, target_y)))

    dx = list(map(lambda x: arrowLength * math.sin(math.radians(x + arrowAngle)), etas))
    dy = list(map(lambda x: arrowLength * math.cos(math.radians(x + arrowAngle)), etas))
    none_spacer = [None for _ in range(len(pointx))]
    arrow_line_x = list(map(lambda x: x[0] - x[1] ** 2 * x[2] * x[3], zip(pointx, signx, signy, dx)))
    arrow_line_y = list(map(lambda x: x[0] - x[1] ** 2 * x[2] * x[3], zip(pointy, signx, signy, dy)))

    arrow_line_1x_coords = list(chain(*zip(pointx, arrow_line_x, none_spacer)))
    arrow_line_1y_coords = list(chain(*zip(pointy, arrow_line_y, none_spacer)))

    dx = list(map(lambda x: arrowLength * math.sin(math.radians(x - arrowAngle)), etas))
    dy = list(map(lambda x: arrowLength * math.cos(math.radians(x - arrowAngle)), etas))
    none_spacer = [None for _ in range(len(pointx))]
    arrow_line_x = list(map(lambda x: x[0] - x[1] ** 2 * x[2] * x[3], zip(pointx, signx, signy, dx)))
    arrow_line_y = list(map(lambda x: x[0] - x[1] ** 2 * x[2] * x[3], zip(pointy, signx, signy, dy)))

    arrow_line_2x_coords = list(chain(*zip(pointx, arrow_line_x, none_spacer)))
    arrow_line_2y_coords = list(chain(*zip(pointy, arrow_line_y, none_spacer)))

    x_arrows = arrow_line_1x_coords + arrow_line_2x_coords
    y_arrows = arrow_line_1y_coords + arrow_line_2y_coords

    return x_arrows, y_arrows

def normalize_dot_size(min_size, max_size, val, min_p, max_p):
    val = val*(max_size-min_size)
    val = val + min_size

    return val

def get_ec(lab, ct_or_p):

    cdict = {'n':'#D12626', 'i':'#51C206', 'p':'#0855CA'}
    if ct_or_p != 'cts':
        cdict = {'s':'#056E5D', 'c':'#7905D7', 'e':'#202A25'}

    return cdict[lab]

def index(request):
    """View function for home page"""

    # Generate counts of pathways and cell types
    num_pathways = Pathway.objects.filter().count()
    num_ss = Pathway.objects.filter(interaction_type="s").count()
    num_ccc = Pathway.objects.filter(interaction_type="c").count()
    num_ecmr = Pathway.objects.filter(interaction_type="e").count()


    num_cell_types = cellClas.objects.all().count()
    num_n = cellClas.objects.filter(cell_type="n").count()
    num_i = cellClas.objects.filter(cell_type="i").count()
    num_p = cellClas.objects.filter(cell_type="p").count()

    # cell type - pathway paris
    num_celltype_pathway_pairs = pathwayAndCelltype.objects.filter(hscPercent__gt=0.049).count()
    num_ligands = Ligand.objects.count()
    num_receptors = Receptor.objects.count()

    num_correlations = pathwayCorrelations.objects.count()
    pos_correlations = pathwayCorrelations.objects.filter(correlation__gt=0).count()
    neg_correlations = pathwayCorrelations.objects.filter(correlation__lt=0).count()

    for_table = pathwayAndCelltype.objects.all().order_by('-averageScore')[:20]

    context = {
        'num_pathways' : num_pathways,
        'num_cell_types' : num_cell_types,
        'num_celltype_pathway_pairs' : num_celltype_pathway_pairs,
        'num_ss': num_ss,
        'num_ccc': num_ccc,
        'num_ecmr': num_ecmr,
        'num_n': num_n,
        'num_i': num_i,
        'num_p': num_p,
        'num_ligands': num_ligands,
        'num_receptors': num_receptors,
        'num_correlations' : num_correlations,
        'pos_correlations' : pos_correlations,
        'neg_correlations' : neg_correlations,
        'for_table' : for_table
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context = context)

def help(request):
    return render(request, 'about.html')

def get_evidence_list(evidences):
    
    evidenceList = evidences.split(";")
        
    evidenceList.pop()
        
    for evidence in evidenceList:
        if ", " in evidence:
            e = evidence.split(", ")
            evidenceList.remove(evidence)
            for item in e:
                evidenceList.append(item)
        
    pmids = {}
    keggs = {}
    pmcs = {}
    
    for i in evidenceList:
        i = i.replace(" ", "")
        if "PMID" in i:
           pmids[i] = "https://pubmed.ncbi.nlm.nih.gov/" + i.split(':')[1]
        elif "KEGG" in i:
            keggs[i] = "https://www.genome.jp/dbget-bin/www_bget?pathway:" + i.split(':')[-1]
        elif "PMC" in i:
            pmcs[i] = "https://www.ncbi.nlm.nih.gov/pmc/articles/" + i
    
    return pmids, keggs, pmcs


def correlations(request):

    ligand_list = Ligand.objects.all()
    genemap, paths = make_gene_map(ligand_list)
    correlations = pathwayCorrelations.objects.all()
    plot_div = make_net_graph_corr(correlations)
    # write some function that parses it like the make_net_graph_JSON function to pass it to render...
    # in the html page, write some javascript that filters the graph based on the form submission
    context = {'genemap':genemap, 'paths':paths, 'plot_div' : plot_div}
    return render(request, 'correlations.html', context)

class PathwayListView(generic.ListView):
    model = Pathway

    def get_context_data(self, **kwargs):
        context = super(PathwayListView, self).get_context_data(**kwargs)
        context['forTable'] = pathwayAndCelltype.objects.all().order_by('-averageScore')[:20]
        return context


interactions/templates/about.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}
<style>

img {
    padding: 0;
    display: block;
    margin: 0 auto;
    max-height: 100%;
    max-width: 100%;
}

.titleLink:hover {
  color: rgb(36, 200, 241);
  background-color: transparent;
}

</style>

<div style="width:90%">
<h1>About HIDE</h1>

<p>
    <b>H</b>ematopoietic Stem Cell <b>I</b>nteraction <b>D</b>ata <b>E</b>xplorer (HIDE) is a database tool for exploration of intercellular communication
    patterns of hematopoietic stem cells in the mouse bone marrow at the single cell level. To start exploring, 
    we provide four starting points: <b>Cell Types</b>, <b>Pathways</b>, <b>Pathway Correlations</b>, and <b>Genes</b>.
</p>

<div class = 'row'>

    <div class = "column">
        <h3>
            <a class="titleLink" href="{% url 'cellclasses' %}">Cell Types</a>
        </h3>
        
        <p>
            Like pathways, cell types are split into three categories: non-hematopoietic, blood
            and immune, and HPCs. Selecting a cell type from the dropdown menu takes you to a page 
            that displays the details of that cell type. These details include: the pathways 
            the given cell type is involved in with HSCs, and a plot to visualize the pathways, 
            fraction of HSCs and interaction scores for the given pathway.
        </p>        
        <img src="{% static "imgs/Slide5.jpg" %}" alt="colormap" style="width:90%;"/>

        </div>

    <div class = "column">
<h3>
    <a class="titleLink" href="{% url 'pathways' %}" color="black">Pathways</a>
</h3>

<p>
    Pathways are split into three categories: secreted signaling, cell-cell contact, 
    and ECM-Receptor. Selecting a pathway from the dropdown menu takes you to a page 
    that displays the details of that pathway. These details include: the pathway's 
    ligands and receptors, the cell types that participate in the pathway with HSCs, 
    and a plot to visualize the fraction of HSCs and interaction scores for  
    the given pathway.
</p>
<img src="{% static "imgs/Slide7.jpg" %}" alt="colormap" style="width:90%;"/>

</div>

</div>

<div class = 'row'>

    <div class = "column">
        <h3>
            <a class="titleLink" href="{% url 'correlations' %}">Pathway Correlations</a>
        </h3>
        
        <p>
        Spearman rank correlations at the individual HSC level were calcualted across all cell type-pathway pairs  (i.e. T-cells Receiving MHC-I).
        Correlations were filtered such that pathways in a pair shared no functional genes.
        They were then filtered such that their adjusted p-value < 0.05. These correlations were then collapsed to pathway level correlations by 
        averaging their cell type-pathway pair correlations and taking the best adjusted p-value.
        </p>
        <img src="{% static "imgs/Slide6.jpg" %}" alt="colormap" style="width:90%;"/>

        </div>

    <div class = "column">
<h3>
    <a class="titleLink" href="{% url 'genes' %}">Genes</a>
</h3>

<p>
    Genes are split into two groups, <b>ligands</b> and <b>receptors</b>. Selecting a gene 
    from the dropdown menu takes you to a page that displays the details of the gene. These 
    details include: the corresponding ligand or receptor, the pathways it is included in, 
    and a link to the corresponding Gene Expression Commons information page (<a href="https://gexc.riken.jp/models/3/genes" target="_blank">Gene Expression Commons</a>).
</p>
<img src="{% static "imgs/Slide8.jpg" %}" alt="colormap" style="width:90%;"/>
</div>

</div>

<h3><a href="https://ronglulab.usc.edu/" target="_blank">Lu Lab</a></h3>

<p>
    This database was designed and deployed by the Rong Lu Lab at the University of Southern 
    California. Click <a href="https://ronglulab.usc.edu/" target="_blank">here</a> for more 
    information about our group.
    <br><br>
    {% load static %} <img src="{% static "imgs/Rong-Lu-Lab-2022-web-by-Chris-Shinn.jpg" %}" alt="Rong Lu Lab Member Photo 2022" style="width:75%;"/>
</p>
</div>

{% endblock %}

interactions/templates/demo-plot.html
<!DOCTYPE HTML>
<html>
    <head>
        <title>Demo plot</title>
    </head>
    <body>
        {% autoescape off %}
            {{ plot_div }}
        {% endautoescape %}
    </body>
</html>

interactions/templates/index.html
{% extends "base_generic.html" %}
{% load humanize %}

{% block content %}


<style>
    .table {
    border-spacing: 0;
    width: 90%;
  }
  
  th {
    cursor: pointer;
  }
  
  th, td {
    text-align: left;
    padding: 16px;
  }
  
  tr:nth-child(even) {
    background-color: #f2f2f2
  }

  thead {color: black;
      background: white; }

  .column_imgs {
    margin-left:auto;
  margin-right:auto;
    width: 80%;
    word-wrap: break-word;
  }

</style>

<div style="width:90%">
    <h1><b>H</b>ematopoietic Stem Cell <b>I</b>nteraction <b>D</b>ata <b>E</b>xplorer (HIDE)</h1>
    <p>Welcome to HIDE, a webiste developed by the <em>Lu Lab</em> to display putative interactions between hematopoietic stem cells and their microenvironment at the single cell level! 
    We provide a few starting points in the left menu, or continue on this page to read more about the data used and how predictions were made.</p>

    <div class="row">
        <div class="column">
            {% load static %}<img src="{% static "imgs/hsc_r_r.png" %}" alt="colormap" style="width:90%;"/>
        </div>

        <div class="column">
            <img src="{% static "imgs/hsc_s_r.png" %}" alt="colormap" style="width:90%;"/>
        </div>

    </div>
<br>
<h2>How predictions were made</h2>
    <p>
        Using CellChat (<a href="https://www.nature.com/articles/s41467-021-21246-9" target="_blank">Jin, et. al</a>), individual HSCs were treated as
        distinct populations and their intercellular communications with their microenvironment were predicted. These predictions are based on scRNA
        expression of corresponding ligands and receptors in the sending and receiving cells respectively. These generated <strong>{{num_celltype_pathway_pairs|intcomma}}</strong> 
        Pathway-Cell Type Pairs with at least 5% HSC activity. The Pathway-Cell Type Pairs were also used to generate <a href="{% url 'correlations' %}">pathway-pathway correlations</a>. 
        These correlations were calculated using a Spearman rank correlations.
    </p>

    <div class="row">
        <div class="column_imgs">
            <img src="{% static "imgs/fig1_niche.png" %}" alt="colormap" style="width:100%;"/>
        </div>
    </div>

<h2>Data used</h2>
    <p>
        Single cell RNA-seq data for hematopoietic stem and progenitor cells were collected in the lab. Single cell RNA-seq data for non-hematopoietic cells
        comes from <a href="https://www.frontiersin.org/articles/10.3389/fcell.2021.622519/full" target="_blank">Dolgalev & Tikhonova</a>.
        Single cell RNA-seq data for blood and immune cells comes from <a href="https://www.nature.com/articles/s41556-019-0439-6" target="_blank">Baccin, et. al</a>. 
        The number of pathways, cell types, and genes used are as follows:
        
        <li><strong><a href="{% url 'cellclasses' %}">Cell Types</a>:</strong> {{num_cell_types}} </li>
        <ul>
            <li>Non-hematopoietic: {{num_n}}</li>
            <li>Blood & Immune: {{num_i}}</li>
            <li>Hematopoietic Progenitor Cells: {{num_p}}</li>
        </ul>

        <li><strong><a href="{% url 'pathways' %}">Pathways</a>:</strong> {{num_pathways}} </li>
        <ul>
            <li>Secreted Signaling: {{num_ss}}</li>
            <li>Cell Cell Contact: {{num_ccc}}</li>
            <li>Extracellular Matrix-Receptor: {{num_ecmr}}</li>
        </ul>
        <li><strong><a href="{% url 'correlations' %}">Pathway correlations</a>:</strong> {{ num_correlations|intcomma }} </li>
                <ul>
                    <li>Positive Correlations: {{ pos_correlations }}</li>
                    <li>Negative Correlations: {{ neg_correlations }}</li>
                </ul>
        <li><strong><a href="{% url 'genes' %}">Ligands</a>:</strong> {{num_ligands}} </li>
        <li><strong><a href="{% url 'genes' %}">Receptors</a>:</strong> {{num_receptors}} </li>
    </p>
    


    <h2>How to use</h2>
    <p>
        See the <a href="{% url 'about' %}">Help</a> page for more information.
    </p>
  </div>

<h2>Summary Table</h2>

Click on a column name to sort
<table id="sortMe" class="table">
    <thead>
      <tr>
        <th>Cell Type</th>
        <th>Communication Type (HSCs are...)</th>
        <th>Pathway Type</th>
        <th>Pathway Name</th>
        <th>Interacting HSC Fraction</th>
        <th>Interaction Score</th>
     </tr>
    </thead>
    <tbody>
      {% for pairs in for_table %}
      <tr>
        <td><a href="{{ pairs.celltype.get_absolute_url }}">{{pairs.celltype.name}}</a></td>
        
        <td>{{ pairs.get_sorr_display }}</td>
        <td><a href="{{ pairs.pathway.get_absolute_url }}">{{pairs.pathway.name}}</a></td>
        <td>{{ pairs.pathway.get_interaction_type_display }}</td>
        <td>{{pairs.hscPercent|floatformat:3}}</td>
        <td>{{pairs.averageScore|floatformat:3}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
<br>
<br>
<br>

    
<script>
// Query the table
  const table = document.getElementById('sortMe');
  
  // Query the headers
  const headers = table.querySelectorAll('th');
  
  // Loop over the headers
  [].forEach.call(headers, function (header, index) {
      header.addEventListener('click', function () {
          // This function will sort the column
          sortColumn(index);
      });
  });
  
  // Query all rows
  const tableBody = table.querySelector('tbody');
  const rows = tableBody.querySelectorAll('tr');
  const transform = function (index, content) {
      // Get the data type of column
      const type = headers[index].getAttribute('data-type');
      switch (type) {
          case 'number':
              return parseFloat(content);
          case 'string':
          default:
              return content;
      }
  };
  const directions = Array.from(headers).map(function (header) {
      return '';
  });
  const sortColumn = function (index) {
      // Clone the rows
      
      // Get the current direction
      const direction = directions[index] || 'asc';
  
      // A factor based on the direction
      const multiplier = (direction === 'asc') ? 1 : -1;
      
      const newRows = Array.from(rows);
      // Sort rows by the content of cells
      newRows.sort(function (rowA, rowB) {
      const cellA = rowA.querySelectorAll('td')[index].innerHTML;
      const cellB = rowB.querySelectorAll('td')[index].innerHTML;
  
      // Transform the content of cells
      const a = transform(index, cellA);
      const b = transform(index, cellB);
  
      // And compare them
      switch (true) {
          case a > b:
              return 1* multiplier;
          case a < b:
              return -1* multiplier;
          case a === b:
              return 0;
      }
  });
      directions[index] = direction === 'asc' ? 'desc' : 'asc';
  
      // Remove old rows
      [].forEach.call(rows, function (row) {
          tableBody.removeChild(row);
      });
  
      // Append new row
      newRows.forEach(function (newRow) {
          tableBody.appendChild(newRow);
      });
  };
  
</script>

{% endblock %}